# common configuration for ALL branches
environment:
  baseversion: '0.7.1'
version: 0.7.1
image: Visual Studio 2017
before_build:
- cmd: nuget restore solrnet.sln
configuration: Release
nuget:
  project_feed: true
build:
  project: solrnet.sln
  verbosity: minimal
  publish_nuget: true
test:
  categories:
    except:
    - Integration
    - OutDated


# here we are going to override common configuration
for:
-
  branches:
    only:
      - master
  version: '%version%'

# override settings for `release-*` branches
-
  branches:
    only:
      - /release-.*/
  version: '%version%.{build}-rc'

# "fall back" configuration for all other branches
- 
  version: '%version%.%baseversion%.{build}-alpha'